let addrs={"2 Watt Avenue":"2",
"4145 Lincoln Way":"7",
"37 Sequoia Way":"2",
"14 Roemer Way":"11",
"23 Glenview Drive":"2",
"25 Buckingham Way":"2",
"27 Hollywood Court":"2",
"31 Arleta Avenue":"6",
"53 Colton Street":"11",
"72 Broad Street":"2",
"76 Newton Street":"2",
"118 Taylor Street":"4",
"129 Girard Street":"6",
"135 Capp Street":"5",
"159 Bright Street":"2",
"159 Sagamore Street":"2",
"165 Amherst Street":"6",
"171 Farallones Street":"2",
"174 Ellis Street":"4",
"191 Evelyn Way":"2",
"201 Charter Oak Avenue":"5",
"205 Clayton Street":"8",
"211 Sweeny Street":"6",
"216 Eddy Street":"4",
"225 30th Street":"1",
"246 McAllister Street":"4",
"255 Woodside Avenue 303":"2",
"259 Broad Street":"2",
"302 Silver Avenue":"6",
"320 Clementina Street":"4",
"330 Cordova Street":"2",
"345 6th Street":"4",
"345 Arguello Boulevard":"1",
"345 6th Street 307":"4",
"350 Ellis Street":"4",
"350 Gaven Street":"6",
"350 University Street":"6",
"355 Faxon Avenue":"2",
"358 21st Avenue 2":"1",
"358 21st Avenue":"1",
"364 4th Avenue":"1",
"365 Fulton Street":"8",
"367 Hale Street":"6",
"370 Valencia Street":"5",
"410 China Basin Street":"5",
"420 Berry Street":"4",
"425 Eddy Street":"4",
"426 Burrows Street":"6",
"465 11th Avenue":"1",
"468 3rd Avenue":"1",
"468 Amherst Street":"6",
"471 19th Avenue":"1",
"491 31st Avenue":"1",
"500 33rd Avenue":"1",
"506 41st Avenue":"11",
"520 Jones Street":"4",
"528 Valencia Street":"5",
"528 Valencia Street 403":"5",
"533 29th Avenue":"1",
"533 29th Avenue ":"1",
"537 Kansas Street":"5",
"562 6th Avenue":"1",
"574 21st Avenue":"1",
"580 Capp Street":"5",
"614 7th Avenue":"1",
"622 Geneva Avenue":"6",
"624 9th Avenue":"1",
"627 21st Avenue":"1",
"629 Larch Way":"8",
"640 Turk Street":"4",
"663 38th Avenue":"1",
"670 Eddy Street":"4",
"688 27th Street":"0",
"696 23rd Avenue":"1",
"701 Golden Gate Avenue":"4",
"705 Frederick Street":"11",
"706 Columbus Avenue":"3",
"711 Pacific Avenue":"3",
"730 Eddy Street":"4",
"735 Ellis Street":"4",
"737 Folsom Street":"4",
"750 5th Avenue":"1",
"770 18th Avenue":"1",
"779 15th Avenue":"1",
"801 Howard Street":"4",
"838 Pacific Avenue":"3",
"848 Kearny Street":"3",
"858 Washington Street":"3",
"875 34th Avenue":"1",
"890 29th Avenue":"1",
"945 Sacramento Street":"3",
"955 Broderick Street":"8",
"990 Polk Street":"4",
"995 Brussels Street":"6",
"1001 Franklin Street":"8",
"1025 Fillmore Street":"8",
"1066 Mission Street":"4",
"1099 Fillmore Street":"8",
"1100 Van Ness Avenue":"4",
"1105 Post Street":"4",
"1201 Golden Gate Avenue":"8",
"1215 Ellis Street":"4",
"1223 Webster Street":"8",
"1234 McAllister Street":"8",
"1234 McAllister Street 2n":"8",
"1240 Fillmore Street":"8",
"1250 Haight Street":"8",
"1250 Pierce Street":"8",
"1285 Monteray Blvd":"2",
"1285 Monterey Boulevard":"2",
"1301 Stevenson Boulevard":"0",
"1310 15th Avenue":"10",
"1316 Stockton Street":"3",
"1321 Mission Street":"4",
"1333 Bush Street":"4",
"1419 48th Avenue":"9",
"1420 Hampshire Street":"5",
"1423 32nd Avenue":"10",
"1426 Rivera Street":"10",
"1444 McAllister Street":"8",
"1458 21st Avenue":"10",
"1499 Webster St":"8",
"1510 Jerrold Avenue":"5",
"1542 36th Avenue":"9",
"1551 Hyde Street":"3",
"1559 27th Avenue":"7",
"1609 Cayuga Avenue":"2",
"1624 Noriega Street":"10",
"1634 41st Avenue":"9",
"1635 23rd Avenue":"10",
"1643 42nd Avenue":"9",
"1645 Pacific Avenue":"3",
"1660 Geary Boulevard":"0",
"1665 Chestnut Street":"3",
"1667 Silver Avenue":"5",
"1667 Silver Avenue 1st floor":"5",
"1671 44th Avenue":"9",
"1675 Scott Street":"0",
"1680 Eddy Street":"8",
"1683 44th Avenue":"9",
"1722 Turk Street":"8",
"1723 Geneva Avenue":"6",
"1731 45th Avenue":"9",
"1735 Steiner Street":"8",
"1750 42nd Avenue":"9",
"1755 O'Farrell Street":"8",
"1770 19th Avenue":"10",
"1790 9th Avenue":"10",
"1797 Ellis Street":"8",
"1814 32nd Avenue":"10",
"1870 36th Avenue":"9",
"1880 Fulton Street":"8",
"1880 Pine Street":"3",
"1900 29th Avenue":"10",
"1927 32nd Avenue":"10",
"1937 20th Avenue":"10",
"1975 45th Avenue":"9",
"2014 34th Avenue":"7",
"2034 34th Avenue":"7",
"2034 43rd Avenue":"9",
"2051 46th Avenue":"9",
"2063 18th Avenue":"10",
"2107 O'Farrell Street":"0",
"2116 17th Avenue":"10",
"2141 Geary Boulevard APT 101":"8",
"2141 Geary Boulevard":"8",
"2143 21st Avenue":"10",
"2179 30th Avenue":"10",
"2187 30th Avenue":"10",
"2191 45th Avenue":"9",
"2220 Turk Boulevard":"2",
"2279 25th Avenue":"10",
"2315 25th Avenue":"10",
"2318 43rd Avenue":"9",
"2330 Post Street 6th Floor":"8",
"2340 Turk Boulevard":"2",
"2351 20th Avenue":"10",
"2442 33rd Avenue":"7",
"2447 19th Avenue":"7",
"2451 Sacramento Street":"3",           
"2456 Geary Boulevard":"8",
"2459 28th Avenue":"10",
"2487 24th Avenue":"10",
"2503 Balboa Street":"1",
"2503 Balboa Street 3":"1",
"2517 Post Street":"8",
"2525 Balboa Street":"1",
"2535 35th Avenue":"7",
"2535 38th Avenue":"7",
"2560 21st Avenue":"10",
"2567 22nd Avenue":"10",
"2595 43rd Avenue":"9",
"2611 34th Avenue":"9",
"2698 California Street Apt C":"8",
"2709 Balboa Street":"1",
"2740 California Street":"8",
"2770 Lombard Street":"3",
"3575 Geary Boulevard":"0",
"3595 Geary Boulevard":"0",
"3627 Moraga Street":"9",
"3683 Peralta Boulevard":"5",
"3981 Alemany Boulevard APT 214":"2",
"4116 Ulloa Street":"9",
"4220 Judah Street":"9",
"4735 California Street":"1",
"4735 California Street 2":"1",
"4830 Mission Street":"2",
"5328 Fulton Street":"1",
"5628 California Street":"1",
"5717 Geary Boulevard":"1",
"5767 Mission Street":"2"
}

let prtObjInfo = {
    "Abele, Arija": {
        "id": "189059",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Abesamis, Purificacion K": {
        "id": "PC10990",
        "room": "3",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Agemso, Woubishet": {
        "id": "490099",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Aldana, Eugenia": {
        "id": "490014",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Anies, Cristeta": {
        "id": "693470",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Arias, Lydia": {
        "id": "664978",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Aubrey, Corrine": {
        "id": "PC24904",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Bajjalieh, Laila": {
        "id": "536349",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Beck, Ora": {
        "id": "632940",
        "room": "3",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Bello, Christopher": {
        "id": "693509",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Bian, John": {
        "id": "645728",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Bishop Robinson, Jacqueline": {
        "id": "173290",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Bolden, Joseph": {
        "id": "534373",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Bonilla, Yolanda": {
        "id": "188622",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Bonner, Patricia": {
        "id": "PC7598",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Briggs, Sharon": {
        "id": "490028",
        "room": "3",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Burr, Sandra": {
        "id": "693544",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Burr, Sandra Jeanne": {
        "id": "693544",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cabrera De Interiano, Elva": {
        "id": "693551",
        "room": "3",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Campbell, Stephan": {
        "id": "PC7599",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Canizalez, Graciela": {
        "id": "173296",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cao, Wan Ran": {
        "id": "195159",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Carlsson, Sally S": {
        "id": "PC8659",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Carroll-Iturralde, Ruth": {
        "id": "490043",
        "room": "3",
        "rt": "11",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Carroll, Robert A": {
        "id": "PC11081",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cassidy, Betty": {
        "id": "693572",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chae, Dong": {
        "id": "632943",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chamberlin, C": {
        "id": "PC8563",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Albert N": {
        "id": "PC27355",
        "room": "3",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Chung Wing": {
        "id": "501606",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, David": {
        "id": "PC11090",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, David L": {
        "id": "693589",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "1045",
        "noAM":"",
        "noPM":""
    },
    "Chan, Kwai-Hin": {
        "id": "181932",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Kwan Har": {
        "id": "501011",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Patricia": {
        "id": "180900",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Phillip": {
        "id": "180886",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Shirlena": {
        "id": "193244",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Sook Wah": {
        "id": "173301",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Suk Ching": {
        "id": "PC8544",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Sylvia W": {
        "id": "PC11099",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chan, Wai Hing": {
        "id": "693594",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chang, Judy": {
        "id": "PC7569",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chau, Polo": {
        "id": "633043",
        "room": "1",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chau, Simon": {
        "id": "PC8459",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chavez Lopez, Humberto": {
        "id": "490079",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chen, Annie": {
        "id": "PC21267",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chen, Buoy Lan": {
        "id": "PC8509",
        "room": "2",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chen, Shun Hui": {
        "id": "490081",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chen, Yan Fang": {
        "id": "181660",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chen, Yiqun": {
        "id": "PC11141",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chen, Zuo Ren": {
        "id": "PC8510",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cheng, Guang Shun": {
        "id": "PC11147",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cheng, James": {
        "id": "PC8986",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":true
    },
    "Cheung, William": {
        "id": "633044",
        "room": "1",
        "rt": "7",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chiang, Kuo Hsiun": {
        "id": "PC27880",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chin, Ang Lin": {
        "id": "PC8511",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chin, Anita": {
        "id": "PC14702",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chou, Sio Cheong": {
        "id": "PC8512",
        "room": "1",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chow, Wan Chung": {
        "id": "PC32911",
        "room": "2",
        "rt": "7",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chow, Yau Soong": {
        "id": "PC11182",
        "room": "1",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chow, Yuliang": {
        "id": "PC11183",
        "room": "1",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Choy, Pui": {
        "id": "PC16213",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chryst, Genn": {
        "id": "PC10374",
        "room": "3",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chu, Chen Xiao": {
        "id": "490373",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chu, Clyde Y": {
        "id": "693624",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chu, Kenneth K": {
        "id": "633045",
        "room": "1",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chu, Kwai Lan": {
        "id": "501607",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chu, Pak C.": {
        "id": "PC11186",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chu, Yin": {
        "id": "693625",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chung, Ann": {
        "id": "645941",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chung, Isaac I": {
        "id": "PC11196",
        "room": "2",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Chung, Suk W": {
        "id": "PC11198",
        "room": "2",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cordova, Julia": {
        "id": "PC14280",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cornel, Rebecca": {
        "id": "490378",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Cruz, Ruben D": {
        "id": "PC11212",
        "room": "2",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Curry, James": {
        "id": "693660",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Dang, Ly K": {
        "id": "597823",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Dang, Tony T": {
        "id": "693664",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Dao, Ngoc Tu": {
        "id": "693665",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Dao, Tran Tu": {
        "id": "693666",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Deguzman, Evangelina": {
        "id": "693680",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Dixon, Myles E": {
        "id": "PC11260",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Dokko, Daniel": {
        "id": "PC26392",
        "room": "3",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Dokko, Kyungwon": {
        "id": "PC19092",
        "room": "3",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Doyle, Thomas": {
        "id": "693698",
        "room": "3",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Duong, Ban": {
        "id": "693703",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Fan, Hongyu": {
        "id": "693731",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Fang, Yue Hua": {
        "id": "PC11294",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ferrell, Wanda": {
        "id": "693735",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Fischer, Felizitas M": {
        "id": "693736",
        "room": "3",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Fung, Lai King": {
        "id": "693757",
        "room": "2",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Fung, Yuk Leung": {
        "id": "PC11312",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Furlough, Loyce": {
        "id": "PC13387",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Gao, Yi Ren": {
        "id": "PC10682",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Garcia Maldonado, Aurelia": {
        "id": "693773",
        "room": "3",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Garcia-Maldonado, Aurelia": {
        "id": "693773",
        "room": "3",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Garcia, Agustin": {
        "id": "693766",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Garcia, Dora": {
        "id": "173312",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Godinez, Luis": {
        "id": "490397",
        "room": "2",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Gormally, Mary Sr.": {
        "id": "PC8518",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Grant, Teri": {
        "id": "173313",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Grossman, Murray": {
        "id": "490400",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Gu, Guan Qun": {
        "id": "194426",
        "room": "1",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Guleng, Ben": {
        "id": "PC33112",
        "room": "3",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Guerra Ayala, Alma": {
        "id": "490404",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Guevara, Judith Teresa": {
        "id": "490406",
        "room": "2",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hang, Mai Su": {
        "id": "PC23147",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Harper, Linda": {
        "id": "PC27638",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Harris, Janet": {
        "id": "693837",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "He, Ting Gui": {
        "id": "693841",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "He, Yu": {
        "id": "693842",
        "room": "2",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Head, Sherrie": {
        "id": "173019",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hellam, Ruben A": {
        "id": "PC11389",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hellam. Ruben, Ruben": {
        "id": "693846",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hernandez, Marcia": {
        "id": "PC8519",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hernandez, Victoria": {
        "id": "491464",
        "room": "3",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ho, Kim": {
        "id": "PC8520",
        "room": "2",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ho, Kim Yee": {
        "id": "PC11401",
        "room": "2",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Horne, Ronald W": {
        "id": "693877",
        "room": "3",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang Tam, Gui Ying": {
        "id": "PC8500",
        "room": "1",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang, Chien Chien": {
        "id": "PC23529",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang, Jing H": {
        "id": "PC8521",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang, Jing Hua": {
        "id": "PC11441",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang, Shao Ming": {
        "id": "492775",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang, Shu Fen F": {
        "id": "492789",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang, Wei Liang": {
        "id": "PC27228",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huang, Zhao Huan": {
        "id": "PC11458",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hubbard, Charlotte": {
        "id": "PC30590",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hui, Wai Chun Ngai": {
        "id": "PC8522",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hung, Mei Shueng": {
        "id": "PC8523",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hung, Mei Sheung": {
        "id": "PC8523",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Huynh, Hi": {
        "id": "PC8524",
        "room": "1",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Hwang, Soon": {
        "id": "PC11053",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Jackson, Kevin": {
        "id": "693904",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "James, Annie": {
        "id": "693907",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Jesse, Pena": {
        "id": "PC9200",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Jiminez, Gloria": {
        "id": "PC13144",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Jin, Xue Lian": {
        "id": "693917",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Johnson, Willie": {
        "id": "PC8525",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Jones, Elaine": {
        "id": "693920",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kelly, Dorothy Jane": {
        "id": "PC8526",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kerfoot, Lori J": {
        "id": "PC11511",
        "room": "2",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Keung, Ping W": {
        "id": "PC8527",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Keung, Ping Wan": {
        "id": "PC11514",
        "room": "2",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kim, Ho": {
        "id": "PC26734",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kim, Hong": {
        "id": "177377",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kim, Lily": {
        "id": "501613",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kong, Fung Kuen": {
        "id": "173352",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kovaleva, Irina S": {
        "id": "PC27361",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kukol, Joanne": {
        "id": "PC30908",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwan, Peo L": {
        "id": "PC8528",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwan, Peo Line": {
        "id": "PC11540",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwock, Ying Bing": {
        "id": "PC11543",
        "room": "1",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwong Chang, Lin Hing": {
        "id": "PC11548",
        "room": "1",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwong, Chang Lin": {
        "id": "693958",
        "room": "1",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwong, Charlie L": {
        "id": "PC34661",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwong, Chi Min": {
        "id": "555550",
        "room": "1",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kwong, Yuk Lin Ng": {
        "id": "PC34662",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Kyang, Won Dokko": {
        "id": "PC26392",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lam, Thomas": {
        "id": "PC8530",
        "room": "1",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lau, Cheng Kun": {
        "id": "PC30593",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lau, Kitwan": {
        "id": "PC8531",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lau, Yuk Yu": {
        "id": "PC20377",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lea, Lai Chuen": {
        "id": "173387",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Alydia": {
        "id": "PC16549",
        "room": "2",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Betty Lan-Yuen": {
        "id": "693977",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Choi Kuen": {
        "id": "PC8532",
        "room": "1",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Fung": {
        "id": "173155",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Gertrude": {
        "id": "PC15238",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Har Tam": {
        "id": "536566",
        "room": "2",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Har": {
        "id": "536566",
        "room": "2",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Lai Yee": {
        "id": "693985",
        "room": "1",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Lap Chow": {
        "id": "693986",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Larry": {
        "id": "693987",
        "room": "3",
        "rt": "11",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, May Jean J": {
        "id": "PC11607",
        "room": "1",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Mui Chun": {
        "id": "173319",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Ngan Chu": {
        "id": "693990",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Shuk F Lee": {
        "id": "PC8534",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lee, Sooja": {
        "id": "693992",
        "room": "1",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lei, Hon Wan": {
        "id": "PC11623",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leong, Steven": {
        "id": "173320",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Frank F": {
        "id": "PC11631",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Hoi Man": {
        "id": "PC11632",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Hung Chun": {
        "id": "PC29600",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Kwong Fat": {
        "id": "491474",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Leisly L": {
        "id": "PC11634",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Ricky H": {
        "id": "PC11637",
        "room": "2",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Ting See": {
        "id": "188077",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Wing Kwai": {
        "id": "694006",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Leung, Wing Sang": {
        "id": "188075",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Li, Kewu": {
        "id": "PC30036",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Li, Wenping": {
        "id": "694010",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Li, Yan Zhi": {
        "id": "PC23066",
        "room": "2",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Liang, Guo Zhi": {
        "id": "PC9633",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Liang, Huan Mei": {
        "id": "PC8535",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Liang, Minan": {
        "id": "501143",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Liang, Sai Huan": {
        "id": "694014",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lin, Chao Ping": {
        "id": "173321",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lipinski, Andrjez": {
        "id": "PC8536",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lipinski, Andrzej Richard": {
        "id": "PC11708",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Liu, Can Yao": {
        "id": "694023",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Liu, Hao": {
        "id": "PC26224",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Logan, Venitta": {
        "id": "PC13057",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lu, Linda": {
        "id": "694043",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lu, Xiong": {
        "id": "694045",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lucas, Vivian": {
        "id": "694046",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luevano, Megan": {
        "id": "PC9615",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luk Chiu, Fung Hin": {
        "id": "PC11763",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luo, Hui Wei": {
        "id": "501602",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luo, Mahjer": {
        "id": "PC23618",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luong, Vu": {
        "id": "694050",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luong, Vu Quan Q": {
        "id": "PC11772",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luu, Muoi": {
        "id": "PC8537",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Luu, To": {
        "id": "491467",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ly, Ha Bich": {
        "id": "555882",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ly, Kha Chay": {
        "id": "PC26647",
        "room": "2",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ly, Mui": {
        "id": "694052",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ly, Trung": {
        "id": "PC7572",
        "room": "1",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lyons, Gregory": {
        "id": "694053",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Lyons, Gregory B. Brent": {
        "id": "PC11780",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ma, Cui Hua": {
        "id": "PC14948",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ma, Helen": {
        "id": "PC17163",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ma, Kwan Shou": {
        "id": "694054",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ma, Rongan": {
        "id": "694055",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mac, Tam": {
        "id": "PC8538",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mac, Tammy Thuy": {
        "id": "PC25540",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Macdonald, Christopher": {
        "id": "PC21137",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Majher, John J.": {
        "id": "694066",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Malek, Hossein": {
        "id": "650270",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Manilla, Danilo": {
        "id": "PC27356",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mao, Lao L": {
        "id": "PC11803",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Martinez, Benedict": {
        "id": "PC14432",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Martinez, Lawrence Benedict": {
        "id": "694085",
        "room": "3",
        "rt": "11",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Matosich, Helen A": {
        "id": "694091",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Matsuo, Emiko": {
        "id": "694092",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mccarthy, Steven": {
        "id": "PC15386",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mckean, Rosemary": {
        "id": "536353",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mederos, Aquileo": {
        "id": "PC10934",
        "room": "3",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mengesha, Hiwan": {
        "id": "694118",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Miao, Bao Fei": {
        "id": "PC24047",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Miller, Marvin": {
        "id": "694124",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Miller, Thomas": {
        "id": "PC8457",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mok, Nai Tin": {
        "id": "PC33115",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Monroy, Alma": {
        "id": "PC9616",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Montoya, Luis Alonzo": {
        "id": "PC11846",
        "room": "3",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Moore, Ernestine": {
        "id": "192111",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Morley, Marilyn": {
        "id": "PC11851",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Moskvychov, Svyatoslav G": {
        "id": "PC29006",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Mui, So Shung": {
        "id": "694158",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Needes, Norman": {
        "id": "PC12578",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ng, Kwai": {
        "id": "694172",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ng, Ping": {
        "id": "694173",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ng, Ping Jan": {
        "id": "694174",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ng, Po San": {
        "id": "694175",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ng, Sai Mun": {
        "id": "646480",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ng, Siu H Yu": {
        "id": "PC11869",
        "room": "1",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ng, Siu Har Yu": {
        "id": "PC8539",
        "room": "1",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Nguyen, Kimtuyen": {
        "id": "PC8540",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Nguyen, Lap Hoang": {
        "id": "PC14281",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Nguyen, Nhanh Thi": {
        "id": "PC14282",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Nudelman, Irina": {
        "id": "694190",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Nunn, Sue Tsin": {
        "id": "694192",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ornano-Lopez, Maria Del Pilar": {
        "id": "PC8542",
        "room": "3",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ornano, Julia": {
        "id": "597822",
        "room": "3",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pal, Gary": {
        "id": "PC14034",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pan, Wiley": {
        "id": "501151",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pascal, Fabian": {
        "id": "694228",
        "room": "",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pascual, Corozan": {
        "id": "PC10922",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Peed, Leatrice": {
        "id": "694236",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pegueros, Sandra": {
        "id": "534380",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pegueros, Sandra Frances": {
        "id": "PC11955",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Penry, Paul": {
        "id": "694240",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Penry, Paul E": {
        "id": "PC11962",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Perkins, Michael C": {
        "id": "694243",
        "room": "2",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Perry, Stephen": {
        "id": "PC21872",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Peterson, Samuel": {
        "id": "694245",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pho, Lina": {
        "id": "PC8543",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Porter, Gregory": {
        "id": "694260",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Pugh, Michael": {
        "id": "PC18970",
        "room": "3",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Quach, Miles": {
        "id": "694264",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ramos, Gladys": {
        "id": "694275",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Randleston, Edward C": {
        "id": "694276",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Randleston, Edward C.": {
        "id": "694276",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Randleston, Edward": {
        "id": "694276",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Rapisura, Herminia": {
        "id": "694280",
        "room": "3",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Rich-French, Jennylynn": {
        "id": "PC27362",
        "room": "3",
        "rt": "11",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Richardson, Mark L": {
        "id": "694295",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Salunga, Marissa": {
        "id": "PC10280",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Scott, Sharon": {
        "id": "PC28672",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Seymour, Mary": {
        "id": "501474",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Shen, Chang Rong": {
        "id": "694359",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Sherman, Doris": {
        "id": "PC21988",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Siu, Wah Bik B": {
        "id": "PC12100",
        "room": "2",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Smiley, Patricia": {
        "id": "597820",
        "room": "2",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Stamps, Ivory": {
        "id": "191703",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Stern, Mark": {
        "id": "694394",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Su Hang, Mai": {
        "id": "PC24048",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Sun, Ruilian": {
        "id": "173331",
        "room": "2",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Swimmer, John": {
        "id": "PC9620",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Takikawa, Noriko": {
        "id": "PC19110",
        "room": "2",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tam, Wai Ken": {
        "id": "490313",
        "room": "1",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tan, Raymond": {
        "id": "694409",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tan, Robert": {
        "id": "PC21037",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tang, Kok Fang": {
        "id": "490311",
        "room": "1",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tang, Nien": {
        "id": "490310",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Taussig, Marie": {
        "id": "173333",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tavakoli Malek, Zahra": {
        "id": "PC8546",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Taylor, Peggy": {
        "id": "694416",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "The, Siang Hoei": {
        "id": "PC12157",
        "room": "3",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tieu, Minh": {
        "id": "694428",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Todd, Terrence Donald": {
        "id": "PC12160",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tong, Kam Siu": {
        "id": "PC8549",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tran, Anh": {
        "id": "PC8453",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tran, Hong": {
        "id": "PC8550",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tran, Hong Thu": {
        "id": "PC12174",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tran, Lien T": {
        "id": "PC24413",
        "room": "1",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tran, Phuoc": {
        "id": "PC12182",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tsui, Shuk Jee": {
        "id": "PC33163",
        "room": "2",
        "rt": "7",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Tu, David": {
        "id": "490307",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Turner, Robert": {
        "id": "PC26226",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Umeukeje, Alice": {
        "id": "635789",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":true,
        "noPM":""
    },
    "Umeukeje, Timothy": {
        "id": "PC8552",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":true,
        "noPM":""
    },
    "Urrutia, Marta Lilia": {
        "id": "PC20378",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Vaccari, Vivian": {
        "id": "694444",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Vasquez, Leticia": {
        "id": "663298",
        "room": "2",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Vass, Tatiana": {
        "id": "173339",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wan, Lai Yin": {
        "id": "PC12239",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wan, Seeyen": {
        "id": "PC30702",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wang, Caishao": {
        "id": "PC8553",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wang, Chun Ling": {
        "id": "490299",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wang, Dao Gang": {
        "id": "195604",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wang, Judy": {
        "id": "694478",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wang, Judy W": {
        "id": "PC12251",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wang, You Lan": {
        "id": "694480",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Washington, Betty": {
        "id": "694487",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Washington, Virginia": {
        "id": "PC13233",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Waters, Reno": {
        "id": "PC26517",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Watt, Kwok Yan Hong": {
        "id": "PC34828",
        "room": "1",
        "rt": "7",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Webster, Margaret": {
        "id": "PC12270",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Webster, Sr. Margaret": {
        "id": "PC8554",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "White, Dale": {
        "id": "PC24282",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Williams, Delores": {
        "id": "PC32811",
        "room": "3",
        "rt": "8",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Williams, Michael": {
        "id": "PC12279",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wilson, Cregg": {
        "id": "PC8479",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wilton, Donald R": {
        "id": "PC14415",
        "room": "2",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Bill Kwok": {
        "id": "PC8555",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Fung Ying": {
        "id": "694519",
        "room": "1",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Gam Fee": {
        "id": "PC8456",
        "room": "2",
        "rt": "6",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Henry H": {
        "id": "PC16301",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Iris": {
        "id": "694520",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, John": {
        "id": "694521",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Kam Sau": {
        "id": "645710",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Lan Ying": {
        "id": "PC27358",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, May Oi": {
        "id": "694522",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, May Seung": {
        "id": "PC29479",
        "room": "1",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Po Kun": {
        "id": "490289",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Shou Chu": {
        "id": "648560",
        "room": "1",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Wai C": {
        "id": "PC8556",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Wong, Yue Yao": {
        "id": "PC25144",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Woo, May": {
        "id": "195073",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Woo, Mu Jie Xie": {
        "id": "PC12313",
        "room": "1",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":true
    },
    "Woods, Renita": {
        "id": "694528",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Xu, Anne": {
        "id": "490281",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Xu, Gen Su": {
        "id": "694535",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Xu, Guang": {
        "id": "PC27495",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Xu, Ziyin": {
        "id": "694537",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yadambat, Baatar": {
        "id": "694538",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yan, Xin Fa": {
        "id": "PC30591",
        "room": "1",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yancey, Norbert": {
        "id": "694540",
        "room": "3",
        "rt": "4",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yang, Feng Lan": {
        "id": "PC12366",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ye, Hui Juan": {
        "id": "PC23067",
        "room": "2",
        "rt": "9",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ye, Wei Hua": {
        "id": "694546",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Ye, Yibin": {
        "id": "694547",
        "room": "1",
        "rt": "10",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yearwood, Eloisa": {
        "id": "PC13918",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yeoh, Khian Heng": {
        "id": "PC8558",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yeung, Linying L": {
        "id": "PC12391",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yim, Wai Hing": {
        "id": "694549",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yin, Shan": {
        "id": "PC15863",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Young, John": {
        "id": "PC30592",
        "room": "3",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yu, Hua Sheng": {
        "id": "PC12413",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yu, Kwai Ha": {
        "id": "694552",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yu, Thomas": {
        "id": "195228",
        "room": "2",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yu, Yi Jun": {
        "id": "PC14750",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yu, Yong Dong": {
        "id": "PC27360",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yuan, Fu Mei": {
        "id": "PC12426",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Yuan, Shun": {
        "id": "694555",
        "room": "1",
        "rt": "2",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zavaleta, Dora": {
        "id": "PC12433",
        "room": "2",
        "rt": "3",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zeng, Hanying": {
        "id": "694564",
        "room": "1",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zeng, HanYing": {
        "id": "694564",
        "room": "1",
        "rt": "5",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zhang Jin Quan": {
        "id": "PC10471",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zhang, De Zhen": {
        "id": "694565",
        "room": "1",
        "rt": "1",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zhang, Jian Quan": {
        "id": "PC10471",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zheng, Ruibo": {
        "id": "PC14283",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zhou, Xing Hua": {
        "id": "PC12485",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    },
    "Zhu, Cui Liang": {
        "id": "694569",
        "room": "",
        "rt": "",
        "comeDay": "",
        "address": "",
        "amTime": "",
        "noAM":"",
        "noPM":""
    }
}
function getForDAR() {
    let res = {};
    Object.keys(prtObjInfo).forEach(prtName => {
        //res={...res,{prtName:prtName.id}}
        res[prtName.toUpperCase()] = prtObjInfo[prtName].id
    })
    return res
}

function getPrtsArr() {
    let prts = [];
    Object.keys(prtObjInfo).forEach(prtInfo => {
        let temp = {}
        temp.name = prtInfo;
        Object.keys(prtObjInfo[prtInfo]).forEach(info => {
            temp[info] = prtObjInfo[prtInfo][info]
            //prts.push(prtInfo[info])
        })

        prts.push(temp)
    })
    return prts;
}
